spring:
  profiles:
    active: local

  jpa:
    #    show-sql: 'true'
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create

  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/db/mybookgal;MODE=MYSQL

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug